import { Deck } from '../card'
import { C } from '../basic-intfs'
/** This class and file are auto-generated do not edit. */
export class EventDeck {
   static deck: Deck = {
      name: 'EventDeck',
      cards: [
        {nreps: 2, type: "Future Event", name: "Increase Distance", cost: 2, step: 3, subtype: null, ext: "Event2", props: {onGetDist: {when: {offerChoice: "+1 Distance?", dist: {add: 1}}}}, path: "Increase-Distance.png"},
        {nreps: 2, type: "Future Event", name: "Adjust Distance 1", cost: 3, step: 3, subtype: null, ext: "Event2", props: {onGetDist: {when: {offerChoice: "Adjust Distance?", chooseDist: {high: 1, low: -1}}}}, path: "Adjust-Distance-1.png"},
        {nreps: 2, type: "Future Event", name: "Adjust Distance 2", cost: 4, step: 3, subtype: null, ext: "Event2", props: {onGetDist: {when: {offerChoice: "Adjust Distance?", chooseDist: {high: 2, low: -2}}}}, path: "Adjust-Distance-2.png"},
        {nreps: 2, type: "Future Event", name: "Next Distance", cost: 3, step: 3, subtype: null, ext: "Event2", props: {onGetDist: {when: {offerChoice: "Adjust Distance?", dist: {set: "nextDistance"}}}}, path: "Next-Distance.png"},
        {nreps: 2, type: "Future Event", name: "A Tax Lawyer", cost: 3, step: 3, subtype: null, ext: "Event2", props: {futureEvent: {undoLastEffect: {subtype: "Tax"}}}, path: "A-Tax-Lawyer.png"},
        {nreps: 2, type: "Future Event", name: "A Good Lawyer", cost: 4, step: 3, subtype: null, ext: "Event2", props: {futureEvent: {undoLastEffect: {or: {type: "Policy", subtype: "Gov"}}}}, path: "A-Good-Lawyer.png"},
        {nreps: 2, type: "Future Event", name: "Draw Another", cost: 4, step: 3, subtype: null, ext: "Event2", props: {futureEvent: {untilDraws: {drawNAdjust: {add: 1}}}}, path: "Draw-Another.png"},
        {nreps: 2, type: "Future Event", name: "Change Direction", cost: 2, step: 3, subtype: null, ext: "Event2", props: {futureEvent: {direction: {set: "nextDirection"}}}, path: "Change-Direction.png"},
        {nreps: 3, type: "Future Event", name: "Choose Direction", cost: 3, step: 3, subtype: null, ext: "Event2", props: {futureEvent: {chooseDir: {N: 0, S: 0, E: 0, W: 0}, direction: {set: "moveDir"}}}, path: "Choose-Direction.png"},
        {nreps: 2, type: "Future Event", name: "Draw Again", cost: 2, step: 3, subtype: null, ext: "Event2", props: {futureEvent: {draws: {add: 1}}}, path: "Draw-Again.png"},
        {nreps: 2, type: "Future Event", name: "Move Again", cost: 4, step: 3, subtype: null, ext: "Event2", props: {futureEvent: {temp: {set: "moveNextDistance"}}}, path: "Move-Again.png"},
        {nreps: 2, type: "Future Event", name: "New Move", cost: 5, step: 3, subtype: null, ext: "Event2", props: {futureEvent: {when: {chooseDir: {N: 0, S: 0, E: 0, W: 0}, temp: {set: "moveNextDistance"}}}}, path: "New-Move.png"},
        {nreps: 2, type: "Future Event", name: "Increased Range", cost: 2, step: 3, subtype: null, ext: "Event2", props: {futureEvent: {rangeAdjustTurn: {add: 1}}}, path: "Increased-Range.png"},
        {nreps: 2, type: "Future Event", name: "Bonanza", cost: 6, step: 3, subtype: null, ext: "Event2", props: {futureEvent: {buys: {add: 1}, builds: {add: 1}, rangeAdjustTurn: {add: 1}}}, path: "Bonanza.png"},
        {nreps: 2, type: "Future Event", name: "Real Estate Deal", cost: 4, step: 3, subtype: null, ext: "Event2", props: {onBuy: {record: "PlayerLastBuy"}, futureEvent: {buy: "PlayerLastBuy"}}, path: "Real-Estate-Deal.png"},
        {nreps: 2, type: "Future Event", name: "Urban Renewal", cost: 3, step: 3, subtype: null, ext: "Event2", props: {futureEvent: {builds: {add: 1}, buys: {add: 1}, doUrbanRenewal: 2}}, path: "Urban-Renewal.png"},
        {nreps: 2, type: "Deferred", name: "Demolition", cost: null, step: 3, subtype: null, ext: "Event", props: {event: {doUrbanRenewal: 2}}, path: "Demolition.png"},
        {nreps: 2, type: "Deferred", name: "Another Move", cost: null, step: 3, subtype: null, ext: "Event", props: {moves: {add: 1}}, path: "Another-Move.png"},
        {nreps: 2, type: "Deferred", name: "Another Buy", cost: null, step: 2, subtype: null, ext: "Event", props: {buys: {add: 1}}, path: "Another-Buy.png"},
        {nreps: 2, type: "Deferred", name: "Another Build", cost: null, step: 2, subtype: null, ext: "Event", props: {builds: {add: 1}}, path: "Another-Build.png"},
        {nreps: 2, type: "Deferred", name: "Buy Discount", cost: null, step: 3, subtype: null, ext: "Event", props: {untilBuys: {costAdjust: {add: -3, min: 0}}}, path: "Buy-Discount.png"},
        {nreps: 2, type: "Deferred", name: "Discount Buy", cost: null, step: 1, subtype: null, ext: "Event", props: {untilBuys: {costAdjust: {sub: "range", min: 1}}}, path: "Discount-Buy.png"},
        {nreps: 2, type: "Deferred", name: "Build Discount", cost: null, step: 3, subtype: null, ext: "Event", props: {untilBuilds: {buildAdjust: {add: -3, min: 0}}}, path: "Build-Discount.png"},
        {nreps: 2, type: "Deferred", name: "Discount Build", cost: null, step: 1, subtype: null, ext: "Event", props: {untilBuilds: {buildAdjust: {sub: "range", min: 1}}}, path: "Discount-Build.png"},
        {nreps: 2, type: "Deferred", name: "Enterprise", cost: null, step: 3, subtype: null, ext: "Event", props: {buys: {add: 1}, builds: {add: 1}, untilTurnEnd: {rangeAdjustTurn: {add: 1}}}, path: "Enterprise.png"},
        {nreps: 1, type: "Event", name: "Time Off", cost: null, step: 1, subtype: "Bonus", ext: "Event", props: {event: {withPlayer: {high_total_cash: {goTo: {subtype: "Home", isOwner: false}}}}}, path: "Time-Off-cash.png"},
        {nreps: 1, type: "Event", name: "Time Off", cost: null, step: 1, subtype: "Bonus", ext: "Event", props: {event: {withPlayer: {high_total_cost: {goTo: {subtype: "Home", isOwner: false}}}}}, path: "Time-Off-property.png"},
        {nreps: 1, type: "Event", name: "Time Off", cost: null, step: 1, subtype: "Bonus", ext: "Event", props: {event: {withPlayer: {high_total_rent: {goTo: {subtype: "Home", isOwner: false}}}}}, path: "Time-Off-rent.png"},
        {nreps: 2, type: "Event", name: "Win Lottery", cost: null, step: 3, subtype: "Bonus", ext: "Event", props: {event: {coins: {add2: "nextDistance"}}}, path: "Win-Lottery.png"},
        {nreps: 2, type: "Event", name: "Go Home", cost: null, step: 1, subtype: "Bonus", ext: "Event", props: {event: {goTo: {subtype: "Home", isOwner: false}, dist: {set: 0}}}, path: "Go-Home.png"},
        {nreps: 2, type: "Event", name: "Income Tax", cost: null, step: 2, subtype: "Tax", ext: "Event", props: {rent: 0.2, event: {withPlayer: true, pay_tax: "total_rent"}}, path: "Income-Tax.png"},
        {nreps: 2, type: "Event", name: "Property Tax", cost: null, step: 2, subtype: "Tax", ext: "Event", props: {rent: 0.2, event: {withPlayer: true, pay_tax: "total_cost"}}, path: "Property-Tax.png"},
        {nreps: 2, type: "Event", name: "Wealth Tax", cost: null, step: 2, subtype: "Tax", ext: "Event", props: {rent: 0.2, event: {withPlayer: true, pay_tax: "total_cash"}}, path: "Wealth-Tax.png"},
        {nreps: 2, type: "Event", name: "Busted", cost: null, step: 2, subtype: "Gov", ext: "Event", props: {event: {withPlayer: {this_player: {when: {goTo: {name: "Jail"}}, else: {buys: {set: 0}, builds: {set: 0}, polis: {set: 0}}}}}}, path: "Busted.png"},
        {nreps: 1, type: "Event", name: "Accounting Fraud", cost: null, step: 2, subtype: "Gov", ext: "Event", props: {event: {withPlayer: {high_total_cash: {when: {goTo: {name: "Jail"}}, else: {buys: {set: 0}, builds: {set: 0}, polis: {set: 0}}}}}}, path: "Accounting-Fraud-cash.png"},
        {nreps: 1, type: "Event", name: "Investment Fraud", cost: null, step: 2, subtype: "Gov", ext: "Event", props: {event: {withPlayer: {high_total_cost: {when: {goTo: {name: "Jail"}}, else: {buys: {set: 0}, builds: {set: 0}, polis: {set: 0}}}}}}, path: "Investment-Fraud-property.png"},
        {nreps: 1, type: "Event", name: "Price Gouging", cost: null, step: 2, subtype: "Gov", ext: "Event", props: {event: {withPlayer: {high_total_rent: {when: {goTo: {name: "Jail"}}, else: {buys: {set: 0}, builds: {set: 0}, polis: {set: 0}}}}}}, path: "Price-Gouging-rent.png"},
        {nreps: 1, type: "Event", name: "Contract Fraud", cost: null, step: 2, subtype: "Gov", ext: "Event", props: {event: {withPlayer: {high_total_roads: {when: {goTo: {name: "Jail"}}, else: {buys: {set: 0}, builds: {set: 0}, polis: {set: 0}}}}}}, path: "Contract-Fraud-roads.png"},
        {nreps: 2, type: "Event", name: "Eminent Domain", cost: null, step: 3, subtype: "Gov", ext: "Event", props: {event: {withPlayer: true, when: {eq: {vp: 0}, withPlayer: {owner: {coins: {add: "cost"}}}, owner: {set: "undefined"}, offerBuyTile: null}}}, path: "Eminent-Domain.png"},
        {nreps: 2, type: "Event", name: "Failed Inspection", cost: null, step: 2, subtype: "Gov", ext: "Event", props: {event: {event: {withPlayer: true, damage: {noRent: true, filter: {range: 0, from: "curPlayerCard"}}}}}, path: "Failed-Inspection.png"},
        {nreps: 1, type: "Event", name: "Earthquake", cost: null, step: 3, subtype: "Damage", ext: "Event", props: {event: {withPlayer: true, damage: {downgrade: 2, filter: {name: "Housing"}}, nextAlignment: true}}, path: "Earthquake.png"},
        {nreps: 1, type: "Event", name: "Major Flooding", cost: null, step: 2, subtype: "Damage", ext: "Event", props: {event: {withPlayer: true, damage: {noRent: true, filter: {range: 1, from: "curPlayerCard"}}}}, path: "Major-Flooding.png"},
        {nreps: 1, type: "Event", name: "Fire Damage", cost: null, step: 3, subtype: "Damage", ext: "Event", props: {event: {withPlayer: true, damage: {coins: -2, filter: {range: 1, from: "curPlayerCard", not: {type: "Road"}}}}}, path: "Fire-Damage.png"},
        {nreps: 1, type: "Event", name: "Biohazard Cleanup", cost: null, step: 3, subtype: "Damage", ext: "Event", props: {event: {withPlayer: true, damage: {downgrade: 2, filter: {name: "Housing"}}}}, path: "Biohazard-Cleanup.png"},
        {nreps: 1, type: "Event", name: "Toxic Spill", cost: null, step: 3, subtype: "Damage", ext: "Event", props: {event: {withPlayer: true, toxicSpill: {range: 2, comp: 2}}}, path: "Toxic-Spill.png"},
        {nreps: 1, type: "Event", name: "Tornado", cost: null, step: 3, subtype: "Damage", ext: "Event", props: {event: {withPlayer: true, tornado: {range: 3, count: 3}}}, path: "Tornado.png"},
   ]
  }}
