import { Deck } from '../card'
import { C } from '../basic-intfs'
/** This class and file are auto-generated do not edit. */
export class TechDeck {
   static deck: Deck = {
      name: 'TechDeck',
      cards: [
        {nreps: 1, type: "Industrial", name: "High Tech", cost: "9+", step: 2, stop: 3, rent: 2, vp: 1, subtype: "Social Network", ext: "High Tech", props: {cost: 9, cardFields: [ "valueToken", "valueTokenCounter", "stopCounter" ], valueToken: 0, valueTokenCounter: {counter: [ "Value", 93, -20 ]}, stopCounter: {counter: [ 0, 0, -104.5, C.coinGold ]}, onStep: {valueToken: {add: 1, max: 6}, rent: {set: 2, add: "valueToken"}, stop: {set: 3, add2: "valueToken"}}, onBuild: {costAdjust: {add: 2, filter: {name: "High Tech"}}, buildAdjust: {add: 2, filter: {name: "High Tech"}}, rentAdjust: {add: 1, filter: {type: [ "Commercial", "Residential" ], range: 2}}}}, path: "High-Tech-Social-Network.png"},
        {nreps: 1, type: "Industrial", name: "High Tech", cost: "9+", step: 2, stop: 3, rent: 2, vp: 1, subtype: "Shiny Devices", ext: "High Tech", props: {cost: 9, cardFields: [ "valueToken", "valueTokenCounter", "stopCounter" ], valueToken: 0, valueTokenCounter: {counter: [ "Value", 93, -20 ]}, stopCounter: {counter: [ 0, 0, -104.5, C.coinGold ]}, onStep: {valueToken: {add: 1, max: 6}, rent: {set: 2, add: "valueToken"}, stop: {set: 3, add2: "valueToken"}}, onBuild: {costAdjust: {add: 2, filter: {name: "High Tech"}}, buildAdjust: {add: 2, filter: {name: "High Tech"}}, rentAdjust: {add: 1, filter: {type: [ "Commercial", "Residential" ], range: 2}}}}, path: "High-Tech-Shiny-Devices.png"},
        {nreps: 1, type: "Industrial", name: "High Tech", cost: "9+", step: 2, stop: 3, rent: 2, vp: 1, subtype: "Online Shopping", ext: "High Tech", props: {cost: 9, cardFields: [ "valueToken", "valueTokenCounter", "stopCounter" ], valueToken: 0, valueTokenCounter: {counter: [ "Value", 93, -20 ]}, stopCounter: {counter: [ 0, 0, -104.5, C.coinGold ]}, onStep: {valueToken: {add: 1, max: 6}, rent: {set: 2, add: "valueToken"}, stop: {set: 3, add2: "valueToken"}}, onBuild: {costAdjust: {add: 2, filter: {name: "High Tech"}}, buildAdjust: {add: 2, filter: {name: "High Tech"}}, rentAdjust: {add: 1, filter: {type: [ "Commercial", "Residential" ], range: 2}}}}, path: "High-Tech-Online-Shopping.png"},
        {nreps: 1, type: "Industrial", name: "High Tech", cost: "9+", step: 2, stop: 3, rent: 2, vp: 1, subtype: "Streaming Video", ext: "High Tech", props: {cost: 9, cardFields: [ "valueToken", "valueTokenCounter", "stopCounter" ], valueToken: 0, valueTokenCounter: {counter: [ "Value", 93, -20 ]}, stopCounter: {counter: [ 0, 0, -104.5, C.coinGold ]}, onStep: {valueToken: {add: 1, max: 6}, rent: {set: 2, add: "valueToken"}, stop: {set: 3, add2: "valueToken"}}, onBuild: {costAdjust: {add: 2, filter: {name: "High Tech"}}, buildAdjust: {add: 2, filter: {name: "High Tech"}}, rentAdjust: {add: 1, filter: {type: [ "Commercial", "Residential" ], range: 2}}}}, path: "High-Tech-Streaming-Video.png"},
        {nreps: 1, type: "Industrial", name: "High Tech", cost: "9+", step: 2, stop: 3, rent: 2, vp: 1, subtype: "Internet Ads", ext: "High Tech", props: {cost: 9, cardFields: [ "valueToken", "valueTokenCounter", "stopCounter" ], valueToken: 0, valueTokenCounter: {counter: [ "Value", 93, -20 ]}, stopCounter: {counter: [ 0, 0, -104.5, C.coinGold ]}, onStep: {valueToken: {add: 1, max: 6}, rent: {set: 2, add: "valueToken"}, stop: {set: 3, add2: "valueToken"}}, onBuild: {costAdjust: {add: 2, filter: {name: "High Tech"}}, buildAdjust: {add: 2, filter: {name: "High Tech"}}, rentAdjust: {add: 1, filter: {type: [ "Commercial", "Residential" ], range: 2}}}}, path: "High-Tech-Internet-Ads.png"},
   ]
  }}
