import { Deck } from '../card'
import { C } from '../basic-intfs'
/** This class and file are auto-generated do not edit. */
export class TransitDeck {
   static deck: Deck = {
      name: 'TransitDeck',
      cards: [
        {nreps: 4, type: "Municipal", name: "Bus Stop", color: "rgb(185,83,0)", cost: 4, step: 0, stop: 1, rent: 1, vp: null, subtype: null, ext: "Transit", props: {onStep: {when: {fromTransit: "Bus Stop", dist: {set: 1}}, else: {dist: {add: -1}}}, onStop: {transitTo: [ {subtype: [ "Transit", "Com-Transit" ]}, {dist: 0}, {roads: true} ]}}, text: "-1 Distance\n\n*Move to next Transit\nor Com-Transit.\nIf that is Bus Stop:\nDistance = 1", textLow: {subtype: "Transit"}, extras: [ {ext: "Transit"}, {ext: "Transit"}, {cardProps: [ {stop: 1}, {onStep: {key0 : [ {when: {key0 : [ {fromTransit: "Bus Stop"}, {dist: {set: 1}} ]}}, {else: {dist: {add: -1}}} ]}}, {onStop: {transitTo: {key0 : [ {subtype: [ "Transit", "Com-Transit" ]}, {dist: 0}, {roads: true} ]}}} ]} ], path: "Bus-Stop.png"},
        {nreps: 4, type: "Municipal", name: "Train Station", color: "rgb(185,83,0)", cost: 5, step: -1, stop: 1, rent: 1, vp: null, subtype: null, ext: "Transit", props: {onStop: {when: [ {chooseDir: {key0 : [ {N: 0}, {S: 0}, {E: 0}, {W: 0} ]}}, {transitTo: {name: "Train Station"}} ]}}, text: "*Go to next\nTrain Station\nin chosen Direction.\nDistance = 1", textLow: {subtype: "Transit"}, extras: [ {ext: "Transit"}, {ext: "Transit"}, {cardProps: [ {stop: 1}, {onStop: {when: {key0 : [ {chooseDir: {key0 : [ {N: 0}, {S: 0}, {E: 0}, {W: 0} ]}}, {transitTo: {name: "Train Station"}} ]}}} ]} ], path: "Train-Station.png"},
        {nreps: 4, type: "Commercial", name: "Transit Hub", color: "rgb(180,120,80)", cost: 6, step: -1, stop: 1, rent: 1, vp: null, subtype: "Com-Transit", ext: "Transit", props: {onStep: {dist: {add: -1}}, onStop: {when: [ {chooseDir: 3}, {payOwner: 3}, {temp: {set: "moveNextDistance"}} ]}, onBuild: {buildAdjust: [ {add: -2}, {filter: {key0 : [ {range: 1}, {onCard: true}, {subtype: [ "Transit" ]} ]}} ]}}, text: "-1 Distance\n*May pay $3 to Move\nnext Distance\nin chosen Direction.", textLow: {vp: 1}, extras: [ {ext: "Transit"}, {textLow: "- $2 to Build\nadjacent Transit"}, {subtype: "Com-Transit"}, {ext: "Transit"}, {cardProps: [ {stop: 1}, {onStep: {dist: {add: -1}}}, {onStop: {when: {key0 : [ {chooseDir: 3}, {payOwner: 3}, {temp: {set: "moveNextDistance"}} ]}}}, {onBuild: {buildAdjust: {key0 : [ {add: -2}, {filter: {key0 : [ {range: 1}, {onCard: true}, {subtype: [ "Transit" ]} ]}} ]}}} ]} ], path: "Transit-Hub.png"},
        {nreps: 4, type: "Commercial", name: "Taxi", color: "rgb(185,83,0)", cost: 6, step: -1, stop: 0, rent: 0, vp: null, subtype: null, ext: "Transit", props: {noStop: true, onStep: {dist: {set: "nextDistance"}, payOwner: {set: "dist"}}}, text: "Use Next Distance\nPay $1 per Distance\nand continue to Move.", textLow: {subtype: "Com-Transit"}, extras: [ {ext: "Transit"}, {image: null}, {ext: "Transit"}, {cardProps: [ {stop: 0}, {rent: 0}, {noStop: true}, {onStep: {key0 : [ {dist: {set: "nextDistance"}}, {payOwner: {set: "dist"}} ]}} ]} ], path: "Taxi.png"},
        {nreps: 4, type: "Municipal", name: "Airport", color: "rgb(180,180,180)", cost: 8, step: 0, stop: 0, rent: 1, vp: "*", subtype: "Transit", ext: "Transit", props: {cardFields: "nthAirportVP", nthAirportVP: {set: [ 0, 5, 3, 1, 0, 0 ]}, noStop: true, vp: {set: "nthAirportVP"}, onStep: {when: {ne: {arrivalFrom: "Airport"}, arrivalFrom: {set: "Airport"}, temp: {set: "rangeToAirport"}, payOwner: {set: "temp", add: "rentAdjust"}, transitTo: {name: "Airport"}}, else: {payOwner: {set: "temp", add: "rentAdjust"}, arrivalFrom: {set: "undefined"}}}}, text: {key0: "Go to next Airport.\nDistance = 1\n\n*To each Airport\npay $1 + $1 per range\nto destination.", size: 45}, textLow: {image: null}, extras: [ {ext: "Transit"}, {vp: "*"}, {textLow: [ "*VP = {5, 3, 1, 0}", {size: 45} ]}, {subtype: "Transit"}, {ext: "Transit"}, {cardProps: [ {cardFields: "nthAirportVP"}, {nthAirportVP: {set: [ 0, 5, 3, 1, 0, 0 ]}}, {stop: 0}, {rent: 1}, {noStop: true}, {vp: {set: "nthAirportVP"}}, {onStep: {key0 : [ {when: {key0 : [ {ne: {arrivalFrom: "Airport"}}, {arrivalFrom: {set: "Airport"}}, {temp: {set: "rangeToAirport"}}, {payOwner: {key0 : [ {set: "temp"}, {add: "rentAdjust"} ]}}, {transitTo: {name: "Airport"}} ]}}, {else: {key0 : [ {payOwner: {key0 : [ {set: "temp"}, {add: "rentAdjust"} ]}}, {arrivalFrom: {set: "undefined"}} ]}} ]}} ]} ], path: "Airport.png"},
   ]
  }}
